version: '3'

services:
  chat2api:
    build: .
    container_name: chat2api
    env_file:
      - .env
    ports:
      - '5005:5005'
    volumes:
      - ./data:/app/data
    restart: unless-stopped
